apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: entando/entando-de-app
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: eap
  build:
    artifacts:
    - image: entando/entando-de-app-eap
      docker:
        dockerfile: Dockerfile.eap
        buildArgs:
          VERSION: "{{ .VERSION}}"
- name: wildfly
  build:
    artifacts:
    - image: entando/entando-de-app-wildfly
      docker:
        dockerfile: Dockerfile.wildfly
        buildArgs:
          VERSION: "{{ .VERSION}}"
