# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  replicaCount: 1
  name: entando-de-app
  repository: docker-registry.default.svc:5000/entando/entando-de-app
  tag: 6.0.6
