# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
operator:
  deployLocally: false
prepareInfrastructure: false
app:
  repository: docker.io/entando/entando-de-app
  tag: 6.0.17
  name: entando-de-app
  webContext: "/entando-de-app"
  replicaCount: 1


