---
# Source: preview/charts/operator/templates/ca-cert-secret.yaml
apiVersion: v1
data:
  ca.crt: >-
    
kind: Secret
metadata:
  name: entando-ca-cert-secret
type: Opaque

---
# Source: preview/charts/operator/templates/tls-secret.yaml
apiVersion: v1
data:
  tls.crt: >-
    
  tls.key: >-
    
kind: Secret
metadata:
  name: entando-tls-secret
type: kubernetes.io/tls

---
# Source: preview/charts/operator/templates/docker-image-info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
  namespace: test-ns
data:
  digital-exchange: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-app-builder-de: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-component-manager: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app: >-
    {"version":"6.0.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-eap: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-wildfly: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-controller: >-
    {"version":"6.0.14","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-plugin-link-controller: >-
    {"version":"6.0.5","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-cluster-infrastructure-controller: >-
    {"version":"6.0.13","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-composite-app-controller: >-
    {"version":"6.0.17","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-controller-coordinator: >-
    {"version":"6.0.50","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-dbjob: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-keycloak-controller: >-
    {"version":"6.0.7","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-plugin-controller: >-
    {"version":"6.0.7","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-service: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-keycloak: >-
    {"version":"6.0.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}

---
# Source: preview/charts/operator/templates/k8s-service-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-k8s-service
  namespace: test-ns
---
# Source: preview/charts/operator/templates/operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-operator
  namespace: test-ns
---
# Source: preview/charts/operator/templates/plugin-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-plugin
  namespace: test-ns
---
# Source: preview/charts/operator/templates/k8s-service-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-k8s-service
  namespace: test-ns
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandokeycloakservers
      - entandokeycloakservers/finalizers
      - entandoclusterinfrastructures
      - entandoclusterinfrastructures/finalizers
      - entandoapps
      - entandoapps/finalizers
      - entandoplugins
      - entandoplugins/finalizers
      - entandoapppluginlinks
      - entandoapppluginlinks/finalizers
      - entandodatabaseservices
      - entandodatabaseservices/finalizers
      - entandocompositeapps
      - entandocompositeapps/finalizers
      - entandodebundles
      - entandodebundles/finalizers
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
# Source: preview/charts/operator/templates/operator-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-operator
  namespace: test-ns
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandokeycloakservers
      - entandokeycloakservers/finalizers
      - entandoclusterinfrastructures
      - entandoclusterinfrastructures/finalizers
      - entandoapps
      - entandoapps/finalizers
      - entandoplugins
      - entandoplugins/finalizers
      - entandoapppluginlinks
      - entandoapppluginlinks/finalizers
      - entandodatabaseservices
      - entandodatabaseservices/finalizers
      - entandocompositeapps
      - entandocompositeapps/finalizers
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
# Source: preview/charts/operator/templates/plugin-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-plugin
  namespace: test-ns
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandoplugins
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
---
# Source: preview/charts/operator/templates/operator-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-operator-rolebinding
  namespace: test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-operator
subjects:
  - kind: ServiceAccount
    name: entando-operator
    namespace: test-ns
---
# Source: preview/charts/operator/templates/plugin-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-plugin-rolebinding
  namespace: test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-plugin
subjects:
  - kind: ServiceAccount
    name: entando-plugin
    namespace: test-ns

---
# Source: preview/charts/operator/templates/deployment.yaml

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: test-operator
  labels:
    draft: draft-app
    chart: "operator-6.0.50"
spec:
  replicas: 1
  selector:
    matchLabels:
      draft: draft-app
      app: test-operator
  template:
    metadata:
      labels:
        draft: draft-app
        app: test-operator
    spec:
      serviceAccountName: entando-operator
      volumes:
      containers:
      - name: operator
        image: "docker.io/entando/entando-k8s-controller-coordinator:6.0.50"
        imagePullPolicy: Always
        volumeMounts:
        env:
          - name: ENTANDO_K8S_OPERATOR_NAMESPACE_TO_OBSERVE
            value: test-ns
          - name: ENTANDO_K8S_OPERATOR_SECURITY_MODE
            value: strict
          - name: ENTANDO_K8S_OPERATOR_SERVICEACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: ENTANDO_DEFAULT_ROUTING_SUFFIX
            value: "apps.serv.run"
          - name: ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT
            value: "true"
          - name: ENTANDO_DOCKER_IMAGE_ORG_FALLBACK
            value: "entando"
          - name: ENTANDO_DOCKER_IMAGE_ORG_OVERRIDE
            value: "entando"
          - name: ENTANDO_DOCKER_IMAGE_VERSION_FALLBACK
            value: "6.0.0"
          - name: ENTANDO_DOCKER_REGISTRY_FALLBACK
            value: "docker.io"
          - name: ENTANDO_DOCKER_REGISTRY_OVERRIDE
            value: "docker.io"
          - name: ENTANDO_K8S_OPERATOR_CONFIGMAP_NAMESPACE
            value: "entando"
          - name: ENTANDO_K8S_OPERATOR_SCOPE
            value: "namespace"
          - name: ENTANDO_K8S_OPERATOR_SECURITY_MODE
            value: "lenient"
          - name: ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS
            value: "600"
          - name: ENTANDO_POD_READINESS_TIMEOUT_SECONDS
            value: "600"
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/EntandoControllerCoordinator.ready
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/EntandoControllerCoordinator.ready
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 512Mi
          
      terminationGracePeriodSeconds: 

---
# Source: preview/templates/entando-composite-app.yaml
kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "test-composite-app"
  namespace: test-ns
entandoStatus:
  serverStatuses: {}
  entandoDeploymentPhase: "requested"
spec:
  components:
    - kind: "EntandoKeycloakServer"
      metadata:
        name: "test-kc"
      spec:
        dbms: none
        isDefault: true
        replicas: 1
    - kind: "EntandoClusterInfrastructure"
      metadata:
        name: "test-eci"
      spec:
        dbms: postgresql
        replicas: 1
        isDefault: true
    - kind: "EntandoApp"
      metadata:
        annotations: {}
        labels: {}
        name: "test"
      spec:
        dbms: postgresql
        replicas: 1
        standardServerImage: wildfly
        ingressPath: /entando-de-app
