# !! File must end with empty line !!
dependencies:

  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: entando-de-app
  repository: file://../entando-de-app
  version: 0.1.0
